[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.1"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
queues = "1.0.2"
uuid = { version = "1.16.0", features = ["v4", "serde" ] }
